POST http://localhost:8080/createpost
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwidXNlcmlkIjoiNjJkNmQzMTYtNjJiMC00YWVkLWFlYTEtNjU0MTI5Y2VkY2ZkIiwiZXhwIjoxNzU5MTUzMTA5LCJpYXQiOjE3NTkxNDU5MDl9.Na3W1JDdBVYQvvpGL-KWv_5VP_y-WEv2pvJXvtm-wLc


{
    "title": "my very first blog post from gibson4",
    "post": "Learning something new every day transforms your mind and your life."

}