GET http://localhost:8080/fetchpost
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAc2l0ZS5jb20iLCJ1c2VyaWQiOiIwOGM3ZDg3Ni0yODA1LTQ3MTAtOGNiMC0yZGVjNTFjZDljMzUiLCJleHAiOjE3NjAzNjQyNTYsImlhdCI6MTc2MDM1NzA1Nn0.--dOVlMzlwcxl0fFkBcr6P4LiqHGcWOa22MYtx7ju4g