GET http://localhost:8080/fetchpost
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwidXNlcmlkIjoiNjJkNmQzMTYtNjJiMC00YWVkLWFlYTEtNjU0MTI5Y2VkY2ZkIiwiZXhwIjoxNzU5MTk4ODE0LCJpYXQiOjE3NTkxOTE2MTR9._uvPNisJSxUIrZxHXy0_Kz13g7-k0FZ1LjI8TmSt6dU