GET http://localhost:8080/fetchpost
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwidXNlcmlkIjoiNjJkNmQzMTYtNjJiMC00YWVkLWFlYTEtNjU0MTI5Y2VkY2ZkIiwiZXhwIjoxNzU5MTk5OTAxLCJpYXQiOjE3NTkxOTI3MDF9.gJCEU1PDnnPaOelj2KKtnxYJcA9l3VHag6C-jfOGW4Q